swagger: '2.0'
info:
  x-ibm-name: tnttest
  title: tnttest
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /tnttest
produces:
  - application/xml
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - xslt:
          title: xslt
          input: false
          source: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<xsl:stylesheet xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" xmlns:dp=\"http://www.datapower.com/extensions\" xmlns:func=\"http://exslt.org/functions\" xmlns:apim=\"http://www.ibm.com/apimanagement\" version=\"1.0\" extension-element-prefixes=\"dp func apim\">\n    <!-- Contains the APIM Functions -->\n    <xsl:import href=\"local:///isp/policy/apim.custom.xsl\"/>\n    <xsl:template match=\"/\">\n\n        <xsl:variable name=\"mqURL\">\n            mq://cap-sg-prd-1.integration.ibmcloud.com:16644?QueueManager=MQDAC01;UserName=mqm_im;Channel=MQDAC01.DP.SVRCONN;ChannelTimeout=10000;RequestQueue=API1IN\n        </xsl:variable>\n\n        <xsl:message terminate=\"no\" dp:priority=\"critical\">\n          <xsl:copy-of select=\"$mqURL\"/>\n        </xsl:message>\n\n\n        <xsl:message terminate=\"no\" dp:priority=\"critical\">\n          <xsl:copy-of select=\"$request\"/>\n        </xsl:message>\n\n        \n          <dp:url-open   ssl-proxy=\"bmcchrisone\" target=\"{normalize-space($mqURL)}\" response=\"responsecode-binary\">\n            \n          </dp:url-open>\n  \n\n\n    </xsl:template>\n</xsl:stylesheet>"
          description: ''
  phase: realized
  gateway: datapower-gateway
paths:
  /path-1:
    post:
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: api_parameter-1
          required: false
          in: body
          schema:
            type: object
definitions: {}
tags: []
consumes:
  - application/xml
